### ISSUE TITLE
Changing the default background color of Grub, splash (plymouth) and GDM (the purple)

### ISSUE THREAD

**Issue by izznogooood** [ubuntu/communitheme-set-default#1]
I have been working on a CLI app to change the purple background of Ubuntu all the way from grub to the gdm login screen.

Draft: https://github.com/izznogooood/yact/blob/master/yact/yact.py

So far all I've been doing is patching the files replacing the color codes using regex and thecolorapi.com. 

The files are:
```
/usr/share/gnome-shell/theme/ubuntu.css
/usr/share/plymouth/themes/ubuntu-logo/ubuntu-logo.plymouth
/usr/share/plymouth/themes/ubuntu-logo/ubuntu-logo.grub
```
The result is:
![](https://media.giphy.com/media/e6bsHvcAGuZh6w2YVC/giphy.gif)

My plan was to implement support for the community-snap in the next release.

After [requesting a classic snap](https://forum.snapcraft.io/t/request-for-classic-confinement-of-snap-yact/6478) I was made aware of alternate an started working on a solution which involved copying and patching the themes, then change them with alternate, which would be the more correct way of doing it. Further more I was referred to your thread asking for the same thing in another thread [here.](https://forum.snapcraft.io/t/classic-confinement-request-communitheme-set-default/5146)
So that got me thinking... Is there a way I can make a tool that can make the change to your CSS permanant. I am not sure how to deal with the plymouth part without replacing the themes and I am not sure I can patch your CSS without you overwriting it in the next release. 

I am thinking in the line of some sort of "tweak light" tool that lets you at least choose the background color. And have you thought of implementing plymouth in to the community theme?

Would you be interested in this and do you think it is possible ?

**Comment by didrocks** [comment]
Hey! Interesting expermimentation. I don't think you can easily do that changing one color of the team, You basically need to repackage from scratch and ship an alternative of all the themes, including plymouth, grub…

Files can't be modified easily from existing packages, as you shouldn't touch system files, and those are css without support (once compiled) to css variables that could be tweaked by the user. Also, as there are a lot of things that are dependant on the base color choice, like icons, letting the user changing the color rather than a well-crafter theme is kind of letting them shooting in their feets as some texts/icons will certainly won't be readable.

You can continue this discussion on the community hub https://community.ubuntu.com, but I personnally think the effort evolved to fork/repackage/follow any changes by reuploading to the distribution is quite high compared to the gain.

**Comment by didrocks** [comment]
(closing as this isn't really an issue/bug)
